include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = BetterWiFiRHPrefs
BetterWiFiRHPrefs_FILES = BWRHRootListController.m
BetterWiFiRHPrefs_FRAMEWORKS = UIKit
BetterWiFiRHPrefs_INSTALL_PATH = /Library/PreferenceBundles
BetterWiFiRHPrefs_CFLAGS = -fobjc-arc
BetterWiFiRHPrefs_LDFLAGS = -undefined dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
