include $(THEOS)/makefiles/common.mk

TOOL_NAME = BandLockLauncher
BandLockLauncher_FILES = main.m
BandLockLauncher_FRAMEWORKS = Foundation
BandLockLauncher_CFLAGS = -fobjc-arc
BandLockLauncher_INSTALL_PATH = /usr/bin
BandLockLauncher_CODESIGN_FLAGS = -SEntitlements.plist

include $(THEOS_MAKE_PATH)/tool.mk
