include $(THEOS)/makefiles/common.mk

TOOL_NAME = BandLockClientProbe
BandLockClientProbe_FILES = main.m
BandLockClientProbe_FRAMEWORKS = Foundation
BandLockClientProbe_CFLAGS = -fobjc-arc
BandLockClientProbe_INSTALL_PATH = /usr/bin

include $(THEOS_MAKE_PATH)/tool.mk
